name: .NET Framework Desktop Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release] # 通常 CI/CD 只构建 Release 版本

    runs-on: windows-latest

    env:
      Solution_Name: TransSkin2Model.sln

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # 1. 安装 .NET Framework 4.5 Developer Pack (Targeting Pack + SDK)
    # 使用 Chocolatey 安装。可能需要接受许可。
    # 如果 4.5 不可用，尝试稍高兼容版本如 4.5.2
    - name: Install .NET Framework 4.5 Developer Pack
      shell: pwsh # 使用 PowerShell
      run: |
        choco install dotnetfx-4.5-dev -y --ignore-checksums
        # 如果上面失败，可以尝试 4.5.2:
        # choco install dotnetfx-4.5.2-dev -y --ignore-checksums
        # 确认环境变量更新 (虽然 choco 通常会处理)
        refreshenv

    # 2. 安装 NuGet CLI
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2
      with:
        nuget-version: 'latest'

    # 3. 添加 MSBuild 到 PATH
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    # 4. 还原 NuGet 包
    - name: Restore NuGet packages
      run: nuget restore $env:Solution_Name

    # 5. 构建解决方案
    - name: Build solution
      run: msbuild $env:Solution_Name /p:Configuration=${{ matrix.configuration }}

    # (可选) 6. 上传构建产物
    - name: Upload build artifacts (Optional)
      uses: actions/upload-artifact@v4
      with:
        name: TransSkin2Model-${{ matrix.configuration }}
        path: TransSkin2Model/bin/${{ matrix.configuration }}/TransSkin2Model.exe # 请确认此路径是否正确
